[package]
name = "kuala/christmas-incremental"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Sift = "csqrl/sift@0.0.9"
React = "jsdotlua/react@17.2.0"
ReactRoblox = "jsdotlua/react-roblox@17.2.0"
Virtualized-List = "jsdotlua/virtualized-list@1.3.5"

Squash = "data-oriented-house/squash@2.4.0"
TableKit = "ffrostflame/tablekit@0.2.4"

Clock = "red-blox/clock@1.0.0"
Collection = "red-blox/collection@1.0.0"
Fetch = "red-blox/fetch@2.0.0"
Future = "red-blox/future@1.0.1"
Guard = "red-blox/guard@1.0.1"
Ratelimit = "red-blox/ratelimit@1.0.1"
Signal = "red-blox/signal@2.0.2"
Spawn = "red-blox/spawn@1.1.0"

Lapis = "nezuo/lapis@0.3.3"
