return table.freeze({
	["Idle"] = { id = "11792539192", markerList = {} },
	["CrouchIdle"] = { id = "12685147595", markerList = {} },

	["Walk"] = { id = "11779406153", markerList = {} },
	["CrouchWalk"] = { id = "12685965027", markerList = {} },

	["Burst"] = { id = "12660611688", markerList = {} },
	["Run"] = { id = "11778729347", markerList = {} },
	["Sprint"] = { id = "11778738288", markerList = {} },

	["Jump1"] = { id = "11897493520", markerList = {} },
	["Jump2"] = { id = "11972227383", markerList = {} },
	["SprintJump1"] = { id = "11972242803", markerList = {} },
	["SprintJump2"] = { id = "11972244586", markerList = {} },
	["SlideJump"] = { id = "12709955494", markerList = {} },

	["Fall"] = { id = "11908461395", markerList = {} },

	["Land"] = { id = "12653246213", markerList = {} },
	["LongLand"] = { id = "11927902254", markerList = {} },

	["SlideStart"] = { id = "11897514142", markerList = {} },
	["Slide"] = { id = "11897514142", markerList = {} },
	["SlideSlope"] = { id = "12685443835", markerList = {} },
})
